apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d9yg8q5yy-go 
  janus-idp.io/tekton: d9yg8q5yy-go
  backstage.io/kubernetes-id: d9yg8q5yy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d9yg8q5yy-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml