apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d9yg8q5yy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d9yg8q5yy-go 
  name: d9yg8q5yy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d9yg8q5yy-go 
